### Register user
POST http://localhost:8000/api/v1/users/
Content-Type: application/json

{
  "username": "test_user",
  "first_name": "Test",
  "last_name": "User",
  "password": "Asd123!@#",
  "email": "user@example.com"
}

### Get Authentication Token
POST http://localhost:8000/api-token-auth/
Content-Type: application/json

{
  "username": "test_user",
  "password": "Asd123!@#"
}

### Get Questions
GET http://localhost:8000/api/v1/mathops/play/
Authorization: Token 546b1afc6d3bd251239467f880acf087a9777f38

### Evaluate Submission
POST http://localhost:8000/api/v1/mathops/play/
Content-Type: application/json
Authorization: Token 546b1afc6d3bd251239467f880acf087a9777f38

{
  "id": "08948126-1d19-4648-9dde-d3b40bc4a159",
  "submitted_result": "10"
}
