site_name: kodomath
site_description: A Backend API for a MVP of an application to learn the basic mathematical operations. Developed for the company KodoMath.
repo_url: https://github.com/girisagar46/KodoMathOps
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/girisagar46">girisagar46</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
