# Generated by Django 3.1.3 on 2020-12-02 13:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Beginner"),
                            (2, "Medium"),
                            (3, "Advanced"),
                            (4, "Completed"),
                        ],
                        default=1,
                        verbose_name="Level",
                    ),
                ),
                (
                    "question",
                    models.JSONField(blank=True, default=dict, verbose_name="question"),
                ),
            ],
            options={
                "verbose_name": "questions categorized by level to show it to students",
                "db_table": "question_bank",
                "index_together": {("id", "level")},
            },
        ),
        migrations.CreateModel(
            name="StudentStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Beginner"),
                            (2, "Medium"),
                            (3, "Advanced"),
                            (4, "Completed"),
                        ],
                        default=1,
                        verbose_name="Level",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "stats on each student",
                "verbose_name_plural": "stats on each students",
                "db_table": "student_stats",
                "get_latest_by": "created_at",
                "index_together": {("user", "level", "updated_at")},
            },
        ),
        migrations.CreateModel(
            name="QuestionTracker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time_to_answer", models.DurationField(default=datetime.timedelta(0))),
                ("submitted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mathops.questionbank",
                    ),
                ),
                (
                    "student_stats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mathops.studentstats",
                    ),
                ),
            ],
            options={
                "verbose_name": "track answers submitted by the students",
                "db_table": "question_tracker",
                "index_together": {("id", "created_at")},
            },
        ),
    ]
